# The Ultimate Guide to Zeyro ML Pipeline

Welcome to the production ML pipeline! This notebook is the definitive guide to generating data, tuning hyperparameters via Optuna, training the Behavioural Finance Score (BFS) and Repayment Propensity Score (RPS) models, and evaluating their metrics and explainability (SHAP).

In [1]:
import os
import sys
import numpy as np
import pandas as pd
from IPython.display import display
import logging

# Include project paths
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '../')))

from python.scoring.fixtures import generate_random_fv
from python.scoring.scoring import compute_rps
from python.training.train_bfs import run as train_bfs
from python.training.train_rps import run as train_rps
from python.training.optuna_tuner import tune_bfs, tune_rps
from python.training.features import BFS_FEATURES, RPS_FEATURES, BFS_TARGET, RPS_TARGET
from sklearn.model_selection import train_test_split

c:\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Dataset Generation
We generate a synthetic dataset of 10,000 rows. The target variable is defaulted_within_90d.

In [2]:
def generate_training_data(n_samples=10000):
    print(f"Generating {n_samples} synthetic samples...")
    records = []
    all_features = set(BFS_FEATURES + RPS_FEATURES)
    
    for i in range(n_samples):
        fv = generate_random_fv(seed=i)
        rps_output = compute_rps(fv)
        pd_val = 1.0 - rps_output.probability
        
        record = {feat: fv.get(feat, 0.0) for feat in all_features}
        np.random.seed(i)
        is_default = int(np.random.rand() < pd_val)
        
        record[BFS_TARGET] = is_default
        if BFS_TARGET != RPS_TARGET:
             record[RPS_TARGET] = is_default
        records.append(record)
        
    df = pd.DataFrame(records)
    return df

df = generate_training_data(10000)
print(f"Target '{BFS_TARGET}' Default Rate: {df[BFS_TARGET].mean()*100:.2f}%")
display(df.head())

Generating 10000 synthetic samples...
Target 'defaulted_within_90d' Default Rate: 37.88%

,income.avg_monthly_credit_inr,quality.data_coverage_days,quality.source_diversity_code,cashflow.avg_days_to_near_zero,savings.recurring_sip_detected,emi.total_monthly_exposure_inr,quality.data_gap_count,income.income_regularity_score,network.p2p_transfer_ratio,cashflow.end_of_month_stress_score,...,emi.emi_to_income_ratio,emi.loan_stacking_signals,emi.bnpl_activity_detected,cashflow.min_balance_30d_inr,cashflow.balance_trend_slope,income.credit_to_debit_ratio,volatility.sudden_behavior_change_score,income.income_trend_90d,emi.missed_emi_signals_count,defaulted_within_90d
0,76264.514719,70.089192,0.0,3.920335,1.0,9994.054119,3.0,0.845857,0.0,0.131030,...,0.122718,1.0,0.0,8740.019526,0.004724,1.473105,0.134311,0.265465,0.0,0
1,28706.776162,83.734524,2.0,7.695130,0.0,27305.551768,3.0,0.775244,0.0,0.398813,...,0.210046,1.0,1.0,4453.742643,-0.097692,1.124507,0.039439,-0.072501,3.0,1
2,36560.997377,87.295987,0.0,4.964224,1.0,7497.053032,3.0,0.603695,0.0,0.164518,...,0.191600,1.0,0.0,10253.454532,-0.045982,0.654531,0.125534,-0.145376,0.0,1
3,62514.000705,45.478874,1.0,1.899341,0.0,25004.313600,2.0,0.374394,0.0,0.256647,...,0.492640,0.0,1.0,17323.992016,-0.064127,1.291290,0.332148,0.145923,2.0,1
4,48427.251796,30.432680,0.0,25.784802,0.0,15251.171260,2.0,0.753858,0.0,0.122978,...,0.028008,0.0,0.0,17613.009952,0.064221,1.330982,0.067797,-0.124784,0.0,0

## 2. Train/Validate/Test Splits
The pipelines natively implement a stratified split.

In [3]:
df_temp, df_test = train_test_split(df, test_size=0.15, stratify=df[BFS_TARGET], random_state=42)
df_train, df_val = train_test_split(df_temp, test_size=0.17647, stratify=df_temp[BFS_TARGET], random_state=42)

split_df = pd.DataFrame({
    "Dataset": ["Train", "Validation", "Test"],
    "Rows": [len(df_train), len(df_val), len(df_test)],
    "Percentage": [f"{len(df_train)/len(df)*100:.1f}%", f"{len(df_val)/len(df)*100:.1f}%", f"{len(df_test)/len(df)*100:.1f}%"]
})
display(split_df)

      Dataset  Rows Percentage
0       Train  7000      70.0%
1  Validation  1500      15.0%
2        Test  1500      15.0%

## 3. Optuna Hyperparameter Tuning (BFS Model)
Optuna conducts a Bayesian search to find optimal hyperparameters.

In [4]:
# To keep this notebook fast, we use n_trials=5. In production, use 50-100.
best_params_bfs = tune_bfs(df, n_trials=5, run_name="bfs_optuna_demo")
print("\n*** BEST PARAMETERS FOUND BY OPTUNA FOR BFS ***")
for k, v in best_params_bfs.items():
    print(f"  {k}: {v}")

================================================================================
 BFS TRAINING RUN | run=bfs_optuna_demo_trial_000 | 2026-07-03T03:55:03Z
================================================================================
[SETUP]  Rows: 10000 | Target rate: 37.88%
[PARAMS] n_estimators=500 | learning_rate=0.0108 | max_depth=8 | min_child_weight=1 | subsample=0.5189 | colsample_bytree=0.9234 | reg_alpha=0.6918 | reg_lambda=0.0018
[SPLIT]  Train: 7000 | Val: 3000 (70/30)
────────────────────────────────────────────────────────────────────────────────
[TRAIN   ] Starting...
C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\xgboost\callback.py:386: UserWarning: [09:25:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[TRAIN   ] Done in 1.6s
[TRAIN]  Best round: 33
────────────────────────────────────────────────────────────────────────────────
[METRICS - TRAIN]
  AUC: 0.8697  KS: 0.5739  GINI: 0.7394  BRIER: 0.2060  AVERAGE_PRECISION: 0.8293
  Threshold=0.50  ACCURACY: 0.6281  PRECISION: 1.0000  RECALL: 0.0185  F1: 0.0363
  TP: 49      TN: 4348    FP: 0       FN: 2603
────────────────────────────────────────────────────────────────────────────────
[METRICS - VALIDATION]
  AUC: 0.6819  KS: 0.2636  GINI: 0.3638  BRIER: 0.2230  AVERAGE_PRECISION: 0.5570
  Threshold=0.50  ACCURACY: 0.6233  PRECISION: 1.0000  RECALL: 0.0053  F1: 0.0105
  TP: 3       TN: 932     FP: 0       FN: 565
────────────────────────────────────────────────────────────────────────────────
[METRICS - TEST (HELD OUT)]
  AUC: 0.6866  KS: 0.3097  GINI: 0.3732  BRIER: 0.2230  AVERAGE_PRECISION: 0.5482
  Threshold=0.50  ACCURACY: 0.6220  PRECISION: 0.6667  RECALL: 0.0035  F1: 0.0070
  TP: 2       TN: 931     FP: 1       FN: 566
────────────────────────────────────────────────────────────────────────────────
[SHAP    ] Starting...
[SHAP    ] Done in 5.3s
────────────────────────────────────────────────────────────────────────────────
[SHAP]   Global importance (top 4):
   1. cashflow.balance_trend_slope (Negative balance trajectory) 0.151075  ████████████████████
   2. income.income_regularity_score (Irregular income pattern) 0.052541  ██████
   3. cashflow.end_of_month_stress_score (Month-end cash flow stress) 0.041320  █████
   4. emi.missed_emi_signals_count (Prior missed EMI signals) 0.027601  ███
────────────────────────────────────────────────────────────────────────────────
[OUTPUT] C:\Users\Admin\AppData\Local\Temp\tmpxgrk17j_\bfs_optuna_demo_trial_000
────────────────────────────────────────────────────────────────────────────────
[DONE]   Total elapsed: 7.2s | Summary: run_summary.json
================================================================================
================================================================================
 BFS TRAINING RUN | run=bfs_optuna_demo_trial_001 | 2026-07-03T03:55:10Z
================================================================================
[SETUP]  Rows: 10000 | Target rate: 37.88%
[PARAMS] n_estimators=1000 | learning_rate=0.0244 | max_depth=7 | min_child_weight=17 | subsample=0.9091 | colsample_bytree=0.5275 | reg_alpha=0.0241 | reg_lambda=0.0012
[SPLIT]  Train: 7000 | Val: 3000 (70/30)
────────────────────────────────────────────────────────────────────────────────
[TRAIN   ] Starting...
C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\xgboost\callback.py:386: UserWarning: [09:25:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[TRAIN   ] Done in 0.2s
[TRAIN]  Best round: 38
────────────────────────────────────────────────────────────────────────────────
[METRICS - TRAIN]
  AUC: 0.8117  KS: 0.4631  GINI: 0.6234  BRIER: 0.2047  AVERAGE_PRECISION: 0.7309
  Threshold=0.50  ACCURACY: 0.6593  PRECISION: 0.9185  RECALL: 0.1105  F1: 0.1972
  TP: 293     TN: 4322    FP: 26      FN: 2359
────────────────────────────────────────────────────────────────────────────────
[METRICS - VALIDATION]
  AUC: 0.6753  KS: 0.2615  GINI: 0.3506  BRIER: 0.2205  AVERAGE_PRECISION: 0.5505
  Threshold=0.50  ACCURACY: 0.6400  PRECISION: 0.7500  RECALL: 0.0739  F1: 0.1346
  TP: 42      TN: 918     FP: 14      FN: 526
────────────────────────────────────────────────────────────────────────────────
[METRICS - TEST (HELD OUT)]
  AUC: 0.6938  KS: 0.3078  GINI: 0.3876  BRIER: 0.2188  AVERAGE_PRECISION: 0.5628
  Threshold=0.50  ACCURACY: 0.6353  PRECISION: 0.6909  RECALL: 0.0669  F1: 0.1220
  TP: 38      TN: 915     FP: 17      FN: 530
────────────────────────────────────────────────────────────────────────────────
[SHAP    ] Starting...
[SHAP    ] Done in 1.1s
────────────────────────────────────────────────────────────────────────────────
[SHAP]   Global importance (top 4):
   1. cashflow.balance_trend_slope (Negative balance trajectory) 0.189076  ████████████████████
   2. income.income_regularity_score (Irregular income pattern) 0.074256  ███████
   3. emi.missed_emi_signals_count (Prior missed EMI signals) 0.063534  ██████
   4. cashflow.end_of_month_stress_score (Month-end cash flow stress) 0.062455  ██████
────────────────────────────────────────────────────────────────────────────────
[OUTPUT] C:\Users\Admin\AppData\Local\Temp\tmpy6imw7fx\bfs_optuna_demo_trial_001
────────────────────────────────────────────────────────────────────────────────
[DONE]   Total elapsed: 1.7s | Summary: run_summary.json
================================================================================
================================================================================
 BFS TRAINING RUN | run=bfs_optuna_demo_trial_002 | 2026-07-03T03:55:11Z
================================================================================
[SETUP]  Rows: 10000 | Target rate: 37.88%
[PARAMS] n_estimators=200 | learning_rate=0.0969 | max_depth=8 | min_child_weight=16 | subsample=0.5815 | colsample_bytree=0.6925 | reg_alpha=0.1066 | reg_lambda=0.0015
[SPLIT]  Train: 7000 | Val: 3000 (70/30)
────────────────────────────────────────────────────────────────────────────────
[TRAIN   ] Starting...
C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\xgboost\callback.py:386: UserWarning: [09:25:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[TRAIN   ] Done in 0.2s
[TRAIN]  Best round: 13
────────────────────────────────────────────────────────────────────────────────
[METRICS - TRAIN]
  AUC: 0.7827  KS: 0.4102  GINI: 0.5654  BRIER: 0.1944  AVERAGE_PRECISION: 0.6856
  Threshold=0.50  ACCURACY: 0.7067  PRECISION: 0.7485  RECALL: 0.3401  F1: 0.4677
  TP: 902     TN: 4045    FP: 303     FN: 1750
────────────────────────────────────────────────────────────────────────────────
[METRICS - VALIDATION]
  AUC: 0.6745  KS: 0.2538  GINI: 0.3490  BRIER: 0.2151  AVERAGE_PRECISION: 0.5542
  Threshold=0.50  ACCURACY: 0.6567  PRECISION: 0.6008  RECALL: 0.2782  F1: 0.3803
  TP: 158     TN: 827     FP: 105     FN: 410
────────────────────────────────────────────────────────────────────────────────
[METRICS - TEST (HELD OUT)]
  AUC: 0.6871  KS: 0.3101  GINI: 0.3742  BRIER: 0.2138  AVERAGE_PRECISION: 0.5452
  Threshold=0.50  ACCURACY: 0.6540  PRECISION: 0.5992  RECALL: 0.2606  F1: 0.3632
  TP: 148     TN: 833     FP: 99      FN: 420
────────────────────────────────────────────────────────────────────────────────
[SHAP    ] Starting...
[SHAP    ] Done in 0.4s
────────────────────────────────────────────────────────────────────────────────
[SHAP]   Global importance (top 4):
   1. cashflow.balance_trend_slope (Negative balance trajectory) 0.364792  ████████████████████
   2. income.income_regularity_score (Irregular income pattern) 0.134187  ███████
   3. cashflow.end_of_month_stress_score (Month-end cash flow stress) 0.107053  █████
   4. emi.missed_emi_signals_count (Prior missed EMI signals) 0.069508  ███
────────────────────────────────────────────────────────────────────────────────
[OUTPUT] C:\Users\Admin\AppData\Local\Temp\tmpppr6btkj\bfs_optuna_demo_trial_002
────────────────────────────────────────────────────────────────────────────────
[DONE]   Total elapsed: 0.9s | Summary: run_summary.json
================================================================================
================================================================================
 BFS TRAINING RUN | run=bfs_optuna_demo_trial_003 | 2026-07-03T03:55:12Z
================================================================================
[SETUP]  Rows: 10000 | Target rate: 37.88%
[PARAMS] n_estimators=400 | learning_rate=0.0365 | max_depth=4 | min_child_weight=8 | subsample=0.6070 | colsample_bytree=0.8052 | reg_alpha=1.2086 | reg_lambda=0.0537
[SPLIT]  Train: 7000 | Val: 3000 (70/30)
────────────────────────────────────────────────────────────────────────────────
[TRAIN   ] Starting...
C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\xgboost\callback.py:386: UserWarning: [09:25:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[TRAIN   ] Done in 0.1s
[TRAIN]  Best round: 7
────────────────────────────────────────────────────────────────────────────────
[METRICS - TRAIN]
  AUC: 0.7307  KS: 0.3425  GINI: 0.4614  BRIER: 0.2247  AVERAGE_PRECISION: 0.6194
  Threshold=0.50  ACCURACY: 0.6211  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 4348    FP: 0       FN: 2652
────────────────────────────────────────────────────────────────────────────────
[METRICS - VALIDATION]
  AUC: 0.6834  KS: 0.2745  GINI: 0.3668  BRIER: 0.2271  AVERAGE_PRECISION: 0.5533
  Threshold=0.50  ACCURACY: 0.6213  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 932     FP: 0       FN: 568
────────────────────────────────────────────────────────────────────────────────
[METRICS - TEST (HELD OUT)]
  AUC: 0.7051  KS: 0.3323  GINI: 0.4102  BRIER: 0.2259  AVERAGE_PRECISION: 0.5865
  Threshold=0.50  ACCURACY: 0.6213  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 932     FP: 0       FN: 568
────────────────────────────────────────────────────────────────────────────────
[SHAP    ] Starting...
[SHAP    ] Done in 0.1s
────────────────────────────────────────────────────────────────────────────────
[SHAP]   Global importance (top 4):
   1. cashflow.balance_trend_slope (Negative balance trajectory) 0.092943  ████████████████████
   2. income.income_regularity_score (Irregular income pattern) 0.038770  ████████
   3. cashflow.end_of_month_stress_score (Month-end cash flow stress) 0.028904  ██████
   4. emi.missed_emi_signals_count (Prior missed EMI signals) 0.016431  ███
────────────────────────────────────────────────────────────────────────────────
[OUTPUT] C:\Users\Admin\AppData\Local\Temp\tmpppwg9_jd\bfs_optuna_demo_trial_003
────────────────────────────────────────────────────────────────────────────────
[DONE]   Total elapsed: 0.5s | Summary: run_summary.json
================================================================================
================================================================================
 BFS TRAINING RUN | run=bfs_optuna_demo_trial_004 | 2026-07-03T03:55:13Z
================================================================================
[SETUP]  Rows: 10000 | Target rate: 37.88%
[PARAMS] n_estimators=900 | learning_rate=0.0161 | max_depth=7 | min_child_weight=11 | subsample=0.6486 | colsample_bytree=0.9592 | reg_alpha=1.3271 | reg_lambda=0.1653
[SPLIT]  Train: 7000 | Val: 3000 (70/30)
────────────────────────────────────────────────────────────────────────────────
[TRAIN   ] Starting...
C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\xgboost\callback.py:386: UserWarning: [09:25:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[TRAIN   ] Done in 0.2s
[TRAIN]  Best round: 24
────────────────────────────────────────────────────────────────────────────────
[METRICS - TRAIN]
  AUC: 0.7774  KS: 0.4055  GINI: 0.5548  BRIER: 0.2137  AVERAGE_PRECISION: 0.6836
  Threshold=0.50  ACCURACY: 0.6281  PRECISION: 0.9804  RECALL: 0.0189  F1: 0.0370
  TP: 50      TN: 4347    FP: 1       FN: 2602
────────────────────────────────────────────────────────────────────────────────
[METRICS - VALIDATION]
  AUC: 0.6785  KS: 0.2620  GINI: 0.3570  BRIER: 0.2224  AVERAGE_PRECISION: 0.5492
  Threshold=0.50  ACCURACY: 0.6233  PRECISION: 0.6364  RECALL: 0.0123  F1: 0.0242
  TP: 7       TN: 928     FP: 4       FN: 561
────────────────────────────────────────────────────────────────────────────────
[METRICS - TEST (HELD OUT)]
  AUC: 0.6960  KS: 0.3157  GINI: 0.3920  BRIER: 0.2212  AVERAGE_PRECISION: 0.5594
  Threshold=0.50  ACCURACY: 0.6227  PRECISION: 0.5833  RECALL: 0.0123  F1: 0.0241
  TP: 7       TN: 927     FP: 5       FN: 561
────────────────────────────────────────────────────────────────────────────────
[SHAP    ] Starting...
[SHAP    ] Done in 1.0s
────────────────────────────────────────────────────────────────────────────────
[SHAP]   Global importance (top 4):
   1. cashflow.balance_trend_slope (Negative balance trajectory) 0.172635  ████████████████████
   2. income.income_regularity_score (Irregular income pattern) 0.058268  ██████
   3. cashflow.end_of_month_stress_score (Month-end cash flow stress) 0.041961  ████
   4. emi.missed_emi_signals_count (Prior missed EMI signals) 0.030657  ███
────────────────────────────────────────────────────────────────────────────────
[OUTPUT] C:\Users\Admin\AppData\Local\Temp\tmpv0v99zvm\bfs_optuna_demo_trial_004
────────────────────────────────────────────────────────────────────────────────
[DONE]   Total elapsed: 1.5s | Summary: run_summary.json
================================================================================

*** BEST PARAMETERS FOUND BY OPTUNA FOR BFS ***
  n_estimators: 400
  learning_rate: 0.03645539920606815
  max_depth: 4
  min_child_weight: 8
  subsample: 0.606987495736368
  colsample_bytree: 0.8052384560854454
  reg_alpha: 1.2085595388604156
  reg_lambda: 0.053651285593500075
  objective: binary:logistic
  eval_metric: auc
  random_state: 42
  n_jobs: -1

## 4. Final BFS Training & Evaluation
Train using optimal parameters.

In [5]:
bfs_result = train_bfs(df, run_name="bfs_prod_v1", xgb_params=best_params_bfs)
print(f"\nArtifacts saved to: {bfs_result['model_path']}")

def display_metrics(result_dict):
    train_m = {k: v for k, v in result_dict['metrics']['train'].items() if not isinstance(v, dict)}
    val_m = {k: v for k, v in result_dict['metrics']['val'].items() if not isinstance(v, dict)}
    test_m = {k: v for k, v in result_dict['metrics']['test'].items() if not isinstance(v, dict)}
    m_df = pd.DataFrame([train_m, val_m, test_m], index=["Train", "Validation", "Test"])
    display(m_df.T)

print("\n--- BFS Core Evaluation Metrics ---")
display_metrics(bfs_result)

print("\n--- Top BFS Features by Global SHAP (Train Set) ---")
display(pd.DataFrame(bfs_result["shap"]["global_train"]))

print("\n--- Top BFS Features by Global SHAP (Test Set) ---")
display(pd.DataFrame(bfs_result["shap"]["global_test"]))

================================================================================
 BFS TRAINING RUN | run=bfs_prod_v1 | 2026-07-03T03:55:20Z
================================================================================
[SETUP]  Rows: 10000 | Target rate: 37.88%
[PARAMS] n_estimators=400 | learning_rate=0.0365 | max_depth=4 | min_child_weight=8 | subsample=0.6070 | colsample_bytree=0.8052 | reg_alpha=1.2086 | reg_lambda=0.0537
[SPLIT]  Train: 7000 | Val: 3000 (70/30)
────────────────────────────────────────────────────────────────────────────────
[TRAIN   ] Starting...
C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\xgboost\callback.py:386: UserWarning: [09:25:20] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[TRAIN   ] Done in 0.2s
[TRAIN]  Best round: 26
────────────────────────────────────────────────────────────────────────────────
[METRICS - TRAIN]
  AUC: 0.7406  KS: 0.3621  GINI: 0.4812  BRIER: 0.2088  AVERAGE_PRECISION: 0.6339
  Threshold=0.50  ACCURACY: 0.6640  PRECISION: 0.7577  RECALL: 0.1663  F1: 0.2727
  TP: 441     TN: 4207    FP: 141     FN: 2211
────────────────────────────────────────────────────────────────────────────────
[METRICS - VALIDATION]
  AUC: 0.6860  KS: 0.2770  GINI: 0.3720  BRIER: 0.2165  AVERAGE_PRECISION: 0.5584
  Threshold=0.50  ACCURACY: 0.6480  PRECISION: 0.6613  RECALL: 0.1444  F1: 0.2370
  TP: 82      TN: 890     FP: 42      FN: 486
────────────────────────────────────────────────────────────────────────────────
[METRICS - TEST (HELD OUT)]
  AUC: 0.7050  KS: 0.3335  GINI: 0.4100  BRIER: 0.2141  AVERAGE_PRECISION: 0.5748
  Threshold=0.50  ACCURACY: 0.6533  PRECISION: 0.6690  RECALL: 0.1673  F1: 0.2676
  TP: 95      TN: 885     FP: 47      FN: 473
────────────────────────────────────────────────────────────────────────────────
[SHAP    ] Starting...
[SHAP    ] Done in 0.3s
────────────────────────────────────────────────────────────────────────────────
[SHAP]   Global importance (top 4):
   1. cashflow.balance_trend_slope (Negative balance trajectory) 0.277471  ████████████████████
   2. income.income_regularity_score (Irregular income pattern) 0.091957  ██████
   3. cashflow.end_of_month_stress_score (Month-end cash flow stress) 0.075392  █████
   4. emi.missed_emi_signals_count (Prior missed EMI signals) 0.045541  ███
────────────────────────────────────────────────────────────────────────────────
[OUTPUT] d:\z-business\artifacts\bfs\bfs_prod_v1
────────────────────────────────────────────────────────────────────────────────
[DONE]   Total elapsed: 0.8s | Summary: run_summary.json
================================================================================

Artifacts saved to: d:\z-business\artifacts\bfs\bfs_prod_v1\model.json

--- BFS Core Evaluation Metrics ---

                       Train Validation      Test
model              bfs_train    bfs_val  bfs_test
threshold                0.5        0.5       0.5
auc                   0.7406      0.686     0.705
ks                    0.3621      0.277    0.3335
gini                  0.4812      0.372      0.41
brier                 0.2088     0.2165    0.2141
average_precision     0.6339     0.5584    0.5748
accuracy               0.664      0.648    0.6533
precision             0.7577     0.6613     0.669
recall                0.1663     0.1444    0.1673
f1                    0.2727      0.237    0.2676
tp                       441         82        95
tn                      4207        890       885
fp                       141         42        47
fn                      2211        486       473

--- Top BFS Features by Global SHAP (Train Set) ---

,feature,mean_shap,reason
0,cashflow.balance_trend_slope,0.278008,Negative balance trajectory
1,income.income_regularity_score,0.090224,Irregular income pattern
2,cashflow.end_of_month_stress_score,0.074474,Month-end cash flow stress
3,emi.missed_emi_signals_count,0.045982,Prior missed EMI signals
4,emi.loan_stacking_signals,0.025878,Multiple new loans in 30 days (stacking)
5,savings.savings_to_income_ratio,0.008202,Insufficient savings buffer
6,network.new_vpa_ratio_30d,0.007098,High proportion of transfers to new unknown co...
7,emi.emi_to_income_ratio,0.006899,High debt-to-income ratio
8,cashflow.min_balance_30d_inr,0.006160,None
9,income.avg_monthly_credit_inr,0.005996,None
10,quality.data_coverage_days,0.005770,None
11,income.credit_to_debit_ratio,0.005370,None
12,cashflow.avg_days_to_near_zero,0.005205,Rapid cash depletion after payday
13,income.income_trend_90d,0.004367,None
14,volatility.sudden_behavior_change_score,0.002955,Sudden spending behaviour change
15,savings.recurring_sip_detected,0.002478,None
16,emi.total_monthly_exposure_inr,0.002377,None
17,quality.data_gap_count,0.001863,None
18,quality.thin_file_flag,0.000715,Insufficient transaction history (thin file)
19,quality.source_diversity_code,0.000399,None

--- Top BFS Features by Global SHAP (Test Set) ---

,feature,mean_shap,reason
0,cashflow.balance_trend_slope,0.277471,Negative balance trajectory
1,income.income_regularity_score,0.091957,Irregular income pattern
2,cashflow.end_of_month_stress_score,0.075392,Month-end cash flow stress
3,emi.missed_emi_signals_count,0.045541,Prior missed EMI signals
4,emi.loan_stacking_signals,0.025228,Multiple new loans in 30 days (stacking)
5,savings.savings_to_income_ratio,0.008082,Insufficient savings buffer
6,network.new_vpa_ratio_30d,0.007209,High proportion of transfers to new unknown co...
7,emi.emi_to_income_ratio,0.006552,High debt-to-income ratio
8,income.avg_monthly_credit_inr,0.005952,None
9,cashflow.min_balance_30d_inr,0.005904,None
10,quality.data_coverage_days,0.005875,None
11,income.credit_to_debit_ratio,0.005441,None
12,cashflow.avg_days_to_near_zero,0.005434,Rapid cash depletion after payday
13,income.income_trend_90d,0.004399,None
14,volatility.sudden_behavior_change_score,0.002981,Sudden spending behaviour change
15,savings.recurring_sip_detected,0.002485,None
16,emi.total_monthly_exposure_inr,0.002166,None
17,quality.data_gap_count,0.001929,None
18,quality.thin_file_flag,0.000697,Insufficient transaction history (thin file)
19,quality.source_diversity_code,0.000413,None

## 5. Optuna Tuning & Training (RPS Model)
Now we run the RPS process.

In [6]:
best_params_rps = tune_rps(df, n_trials=5, run_name="rps_optuna_demo")
print("\n*** BEST PARAMETERS FOUND BY OPTUNA FOR RPS ***")
for k, v in best_params_rps.items():
    print(f"  {k}: {v}")

rps_result = train_rps(df, run_name="rps_prod_v1", xgb_params=best_params_rps)

print("\n--- RPS Core Evaluation Metrics ---")
display_metrics(rps_result)

print("\n--- Top RPS Features by Global SHAP (Train Set) ---")
display(pd.DataFrame(rps_result["shap"]["global_train"]))

print("\n--- Top RPS Features by Global SHAP (Test Set) ---")
display(pd.DataFrame(rps_result["shap"]["global_test"]))

================================================================================
 RPS TRAINING RUN | run=rps_optuna_demo_trial_000 | 2026-07-03T03:55:42Z
================================================================================
[SETUP]  Rows: 10000 | Target rate: 37.88%
[PARAMS] n_estimators=300 | learning_rate=0.0204 | max_depth=7 | min_child_weight=11 | subsample=0.6009 | colsample_bytree=0.6348 | reg_alpha=0.2986 | reg_lambda=2.2920
[SPLIT]  Train: 7000 | Val: 3000 (70/30)
────────────────────────────────────────────────────────────────────────────────
[TRAIN   ] Starting...
C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\xgboost\callback.py:386: UserWarning: [09:25:42] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[TRAIN   ] Done in 0.1s
[TRAIN]  Best round: 11
────────────────────────────────────────────────────────────────────────────────
[METRICS - TRAIN]
  AUC: 0.7575  KS: 0.3754  GINI: 0.5150  BRIER: 0.2250  AVERAGE_PRECISION: 0.6507
  Threshold=0.50  ACCURACY: 0.6211  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 4348    FP: 0       FN: 2652
────────────────────────────────────────────────────────────────────────────────
[METRICS - VALIDATION]
  AUC: 0.6913  KS: 0.2799  GINI: 0.3826  BRIER: 0.2277  AVERAGE_PRECISION: 0.5756
  Threshold=0.50  ACCURACY: 0.6213  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 932     FP: 0       FN: 568
────────────────────────────────────────────────────────────────────────────────
[METRICS - TEST (HELD OUT)]
  AUC: 0.7020  KS: 0.3356  GINI: 0.4040  BRIER: 0.2274  AVERAGE_PRECISION: 0.5711
  Threshold=0.50  ACCURACY: 0.6213  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 932     FP: 0       FN: 568
────────────────────────────────────────────────────────────────────────────────
[SHAP    ] Starting...
[SHAP    ] Done in 0.3s
────────────────────────────────────────────────────────────────────────────────
[SHAP]   Global importance (top 4):
   1. cashflow.balance_trend_slope (Negative balance trajectory) 0.079873  ████████████████████
   2. income.income_regularity_score (Irregular income pattern) 0.027415  ██████
   3. cashflow.end_of_month_stress_score (Month-end cash flow stress) 0.022538  █████
   4. emi.missed_emi_signals_count (Prior missed EMI signals) 0.017362  ████
────────────────────────────────────────────────────────────────────────────────
[OUTPUT] C:\Users\Admin\AppData\Local\Temp\tmpmjlb5w73\rps_optuna_demo_trial_000
────────────────────────────────────────────────────────────────────────────────
[DONE]   Total elapsed: 0.7s | Summary: run_summary.json
================================================================================
================================================================================
 RPS TRAINING RUN | run=rps_optuna_demo_trial_001 | 2026-07-03T03:55:43Z
================================================================================
[SETUP]  Rows: 10000 | Target rate: 37.88%
[PARAMS] n_estimators=600 | learning_rate=0.0102 | max_depth=7 | min_child_weight=14 | subsample=0.5704 | colsample_bytree=0.7237 | reg_alpha=0.0169 | reg_lambda=0.0153
[SPLIT]  Train: 7000 | Val: 3000 (70/30)
────────────────────────────────────────────────────────────────────────────────
[TRAIN   ] Starting...
C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\xgboost\callback.py:386: UserWarning: [09:25:43] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[TRAIN   ] Done in 0.1s
[TRAIN]  Best round: 11
────────────────────────────────────────────────────────────────────────────────
[METRICS - TRAIN]
  AUC: 0.7506  KS: 0.3599  GINI: 0.5012  BRIER: 0.2296  AVERAGE_PRECISION: 0.6419
  Threshold=0.50  ACCURACY: 0.6211  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 4348    FP: 0       FN: 2652
────────────────────────────────────────────────────────────────────────────────
[METRICS - VALIDATION]
  AUC: 0.6855  KS: 0.2701  GINI: 0.3710  BRIER: 0.2311  AVERAGE_PRECISION: 0.5675
  Threshold=0.50  ACCURACY: 0.6213  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 932     FP: 0       FN: 568
────────────────────────────────────────────────────────────────────────────────
[METRICS - TEST (HELD OUT)]
  AUC: 0.6995  KS: 0.3209  GINI: 0.3990  BRIER: 0.2308  AVERAGE_PRECISION: 0.5677
  Threshold=0.50  ACCURACY: 0.6213  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 932     FP: 0       FN: 568
────────────────────────────────────────────────────────────────────────────────
[SHAP    ] Starting...
[SHAP    ] Done in 0.4s
────────────────────────────────────────────────────────────────────────────────
[SHAP]   Global importance (top 4):
   1. cashflow.balance_trend_slope (Negative balance trajectory) 0.044299  ████████████████████
   2. income.income_regularity_score (Irregular income pattern) 0.015007  ██████
   3. cashflow.end_of_month_stress_score (Month-end cash flow stress) 0.013152  █████
   4. emi.missed_emi_signals_count (Prior missed EMI signals) 0.009193  ████
────────────────────────────────────────────────────────────────────────────────
[OUTPUT] C:\Users\Admin\AppData\Local\Temp\tmpoc2oks63\rps_optuna_demo_trial_001
────────────────────────────────────────────────────────────────────────────────
[DONE]   Total elapsed: 0.7s | Summary: run_summary.json
================================================================================
================================================================================
 RPS TRAINING RUN | run=rps_optuna_demo_trial_002 | 2026-07-03T03:55:43Z
================================================================================
[SETUP]  Rows: 10000 | Target rate: 37.88%
[PARAMS] n_estimators=700 | learning_rate=0.0161 | max_depth=4 | min_child_weight=8 | subsample=0.6464 | colsample_bytree=0.7421 | reg_alpha=0.0216 | reg_lambda=1.3727
[SPLIT]  Train: 7000 | Val: 3000 (70/30)
────────────────────────────────────────────────────────────────────────────────
[TRAIN   ] Starting...
C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\xgboost\callback.py:386: UserWarning: [09:25:43] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[TRAIN   ] Done in 0.1s
[TRAIN]  Best round: 11
────────────────────────────────────────────────────────────────────────────────
[METRICS - TRAIN]
  AUC: 0.7301  KS: 0.3388  GINI: 0.4602  BRIER: 0.2280  AVERAGE_PRECISION: 0.6164
  Threshold=0.50  ACCURACY: 0.6211  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 4348    FP: 0       FN: 2652
────────────────────────────────────────────────────────────────────────────────
[METRICS - VALIDATION]
  AUC: 0.6878  KS: 0.2726  GINI: 0.3756  BRIER: 0.2293  AVERAGE_PRECISION: 0.5675
  Threshold=0.50  ACCURACY: 0.6213  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 932     FP: 0       FN: 568
────────────────────────────────────────────────────────────────────────────────
[METRICS - TEST (HELD OUT)]
  AUC: 0.7045  KS: 0.3286  GINI: 0.4090  BRIER: 0.2289  AVERAGE_PRECISION: 0.5778
  Threshold=0.50  ACCURACY: 0.6213  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 932     FP: 0       FN: 568
────────────────────────────────────────────────────────────────────────────────
[SHAP    ] Starting...
[SHAP    ] Done in 0.1s
────────────────────────────────────────────────────────────────────────────────
[SHAP]   Global importance (top 4):
   1. cashflow.balance_trend_slope (Negative balance trajectory) 0.066530  ████████████████████
   2. income.income_regularity_score (Irregular income pattern) 0.019821  █████
   3. cashflow.end_of_month_stress_score (Month-end cash flow stress) 0.017729  █████
   4. emi.missed_emi_signals_count (Prior missed EMI signals) 0.012788  ███
────────────────────────────────────────────────────────────────────────────────
[OUTPUT] C:\Users\Admin\AppData\Local\Temp\tmprcn0_bu6\rps_optuna_demo_trial_002
────────────────────────────────────────────────────────────────────────────────
[DONE]   Total elapsed: 0.4s | Summary: run_summary.json
================================================================================
================================================================================
 RPS TRAINING RUN | run=rps_optuna_demo_trial_003 | 2026-07-03T03:55:44Z
================================================================================
[SETUP]  Rows: 10000 | Target rate: 37.88%
[PARAMS] n_estimators=800 | learning_rate=0.0390 | max_depth=5 | min_child_weight=19 | subsample=0.6084 | colsample_bytree=0.8505 | reg_alpha=0.0016 | reg_lambda=0.0690
[SPLIT]  Train: 7000 | Val: 3000 (70/30)
────────────────────────────────────────────────────────────────────────────────
[TRAIN   ] Starting...
C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\xgboost\callback.py:386: UserWarning: [09:25:44] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[TRAIN   ] Done in 0.1s
[TRAIN]  Best round: 11
────────────────────────────────────────────────────────────────────────────────
[METRICS - TRAIN]
  AUC: 0.7354  KS: 0.3468  GINI: 0.4708  BRIER: 0.2175  AVERAGE_PRECISION: 0.6184
  Threshold=0.50  ACCURACY: 0.6293  PRECISION: 0.8701  RECALL: 0.0253  F1: 0.0491
  TP: 67      TN: 4338    FP: 10      FN: 2585
────────────────────────────────────────────────────────────────────────────────
[METRICS - VALIDATION]
  AUC: 0.6852  KS: 0.2692  GINI: 0.3704  BRIER: 0.2218  AVERAGE_PRECISION: 0.5599
  Threshold=0.50  ACCURACY: 0.6260  PRECISION: 0.7333  RECALL: 0.0194  F1: 0.0377
  TP: 11      TN: 928     FP: 4       FN: 557
────────────────────────────────────────────────────────────────────────────────
[METRICS - TEST (HELD OUT)]
  AUC: 0.7000  KS: 0.3236  GINI: 0.4000  BRIER: 0.2206  AVERAGE_PRECISION: 0.5723
  Threshold=0.50  ACCURACY: 0.6280  PRECISION: 0.9167  RECALL: 0.0194  F1: 0.0379
  TP: 11      TN: 931     FP: 1       FN: 557
────────────────────────────────────────────────────────────────────────────────
[SHAP    ] Starting...
[SHAP    ] Done in 0.2s
────────────────────────────────────────────────────────────────────────────────
[SHAP]   Global importance (top 4):
   1. cashflow.balance_trend_slope (Negative balance trajectory) 0.167564  ████████████████████
   2. income.income_regularity_score (Irregular income pattern) 0.062464  ███████
   3. cashflow.end_of_month_stress_score (Month-end cash flow stress) 0.047695  █████
   4. emi.missed_emi_signals_count (Prior missed EMI signals) 0.044546  █████
────────────────────────────────────────────────────────────────────────────────
[OUTPUT] C:\Users\Admin\AppData\Local\Temp\tmpn6yzp890\rps_optuna_demo_trial_003
────────────────────────────────────────────────────────────────────────────────
[DONE]   Total elapsed: 0.5s | Summary: run_summary.json
================================================================================
================================================================================
 RPS TRAINING RUN | run=rps_optuna_demo_trial_004 | 2026-07-03T03:55:44Z
================================================================================
[SETUP]  Rows: 10000 | Target rate: 37.88%
[PARAMS] n_estimators=800 | learning_rate=0.0447 | max_depth=7 | min_child_weight=16 | subsample=0.8839 | colsample_bytree=0.7812 | reg_alpha=7.8032 | reg_lambda=1.1990
[SPLIT]  Train: 7000 | Val: 3000 (70/30)
────────────────────────────────────────────────────────────────────────────────
[TRAIN   ] Starting...
C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\xgboost\callback.py:386: UserWarning: [09:25:44] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[TRAIN   ] Done in 0.2s
[TRAIN]  Best round: 67
────────────────────────────────────────────────────────────────────────────────
[METRICS - TRAIN]
  AUC: 0.7557  KS: 0.3769  GINI: 0.5114  BRIER: 0.1948  AVERAGE_PRECISION: 0.6486
  Threshold=0.50  ACCURACY: 0.7043  PRECISION: 0.6810  RECALL: 0.4129  F1: 0.5141
  TP: 1095    TN: 3835    FP: 513     FN: 1557
────────────────────────────────────────────────────────────────────────────────
[METRICS - VALIDATION]
  AUC: 0.6878  KS: 0.2730  GINI: 0.3756  BRIER: 0.2113  AVERAGE_PRECISION: 0.5710
  Threshold=0.50  ACCURACY: 0.6627  PRECISION: 0.5866  RECALL: 0.3697  F1: 0.4536
  TP: 210     TN: 784     FP: 148     FN: 358
────────────────────────────────────────────────────────────────────────────────
[METRICS - TEST (HELD OUT)]
  AUC: 0.7033  KS: 0.3262  GINI: 0.4066  BRIER: 0.2080  AVERAGE_PRECISION: 0.5749
  Threshold=0.50  ACCURACY: 0.6827  PRECISION: 0.6329  RECALL: 0.3856  F1: 0.4792
  TP: 219     TN: 805     FP: 127     FN: 349
────────────────────────────────────────────────────────────────────────────────
[SHAP    ] Starting...
[SHAP    ] Done in 1.3s
────────────────────────────────────────────────────────────────────────────────
[SHAP]   Global importance (top 4):
   1. cashflow.balance_trend_slope (Negative balance trajectory) 0.505909  ████████████████████
   2. income.income_regularity_score (Irregular income pattern) 0.180016  ███████
   3. cashflow.end_of_month_stress_score (Month-end cash flow stress) 0.134871  █████
   4. emi.missed_emi_signals_count (Prior missed EMI signals) 0.124329  ████
────────────────────────────────────────────────────────────────────────────────
[OUTPUT] C:\Users\Admin\AppData\Local\Temp\tmpzurqk02l\rps_optuna_demo_trial_004
────────────────────────────────────────────────────────────────────────────────
[DONE]   Total elapsed: 1.8s | Summary: run_summary.json
================================================================================
================================================================================
 RPS TRAINING RUN | run=rps_prod_v1 | 2026-07-03T03:55:46Z
================================================================================
[SETUP]  Rows: 10000 | Target rate: 37.88%
[PARAMS] n_estimators=300 | learning_rate=0.0204 | max_depth=7 | min_child_weight=11 | subsample=0.6009 | colsample_bytree=0.6348 | reg_alpha=0.2986 | reg_lambda=2.2920
[SPLIT]  Train: 7000 | Val: 3000 (70/30)
────────────────────────────────────────────────────────────────────────────────
[TRAIN   ] Starting...
C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\xgboost\callback.py:386: UserWarning: [09:25:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  self.starting_round = model.num_boosted_rounds()
[TRAIN   ] Done in 0.1s
[TRAIN]  Best round: 11

*** BEST PARAMETERS FOUND BY OPTUNA FOR RPS ***
  n_estimators: 300
  learning_rate: 0.02043817688355324
  max_depth: 7
  min_child_weight: 11
  subsample: 0.6009472862670099
  colsample_bytree: 0.6348446478944421
  reg_alpha: 0.2985668800476883
  reg_lambda: 2.2919951507022556
  objective: binary:logistic
  eval_metric: auc
  random_state: 42
  n_jobs: -1

────────────────────────────────────────────────────────────────────────────────
[METRICS - TRAIN]
  AUC: 0.7575  KS: 0.3754  GINI: 0.5150  BRIER: 0.2250  AVERAGE_PRECISION: 0.6507
  Threshold=0.50  ACCURACY: 0.6211  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 4348    FP: 0       FN: 2652
────────────────────────────────────────────────────────────────────────────────
[METRICS - VALIDATION]
  AUC: 0.6913  KS: 0.2799  GINI: 0.3826  BRIER: 0.2277  AVERAGE_PRECISION: 0.5756
  Threshold=0.50  ACCURACY: 0.6213  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 932     FP: 0       FN: 568
────────────────────────────────────────────────────────────────────────────────
[METRICS - TEST (HELD OUT)]
  AUC: 0.7020  KS: 0.3356  GINI: 0.4040  BRIER: 0.2274  AVERAGE_PRECISION: 0.5711
  Threshold=0.50  ACCURACY: 0.6213  PRECISION: 0.0000  RECALL: 0.0000  F1: 0.0000
  TP: 0       TN: 932     FP: 0       FN: 568
────────────────────────────────────────────────────────────────────────────────
[SHAP    ] Starting...
[SHAP    ] Done in 0.4s
────────────────────────────────────────────────────────────────────────────────
[SHAP]   Global importance (top 4):
   1. cashflow.balance_trend_slope (Negative balance trajectory) 0.079873  ████████████████████
   2. income.income_regularity_score (Irregular income pattern) 0.027415  ██████
   3. cashflow.end_of_month_stress_score (Month-end cash flow stress) 0.022538  █████
   4. emi.missed_emi_signals_count (Prior missed EMI signals) 0.017362  ████
────────────────────────────────────────────────────────────────────────────────
[OUTPUT] d:\z-business\artifacts\rps\rps_prod_v1
────────────────────────────────────────────────────────────────────────────────
[DONE]   Total elapsed: 0.8s | Summary: run_summary.json
================================================================================

--- RPS Core Evaluation Metrics ---

                       Train Validation      Test
model              rps_train    rps_val  rps_test
threshold                0.5        0.5       0.5
auc                   0.7575     0.6913     0.702
ks                    0.3754     0.2799    0.3356
gini                   0.515     0.3826     0.404
brier                  0.225     0.2277    0.2274
average_precision     0.6507     0.5756    0.5711
accuracy              0.6211     0.6213    0.6213
precision                0.0        0.0       0.0
recall                   0.0        0.0       0.0
f1                       0.0        0.0       0.0
tp                         0          0         0
tn                      4348        932       932
fp                         0          0         0
fn                      2652        568       568

--- Top RPS Features by Global SHAP (Train Set) ---

,feature,mean_shap,reason
0,cashflow.balance_trend_slope,0.079976,Negative balance trajectory
1,income.income_regularity_score,0.027114,Irregular income pattern
2,cashflow.end_of_month_stress_score,0.022337,Month-end cash flow stress
3,emi.missed_emi_signals_count,0.017533,Prior missed EMI signals
4,cashflow.min_balance_30d_inr,0.010848,None
5,emi.loan_stacking_signals,0.006674,Multiple new loans in 30 days (stacking)
6,cashflow.avg_days_to_near_zero,0.005901,Rapid cash depletion after payday
7,emi.bnpl_activity_detected,0.000472,None

--- Top RPS Features by Global SHAP (Test Set) ---

,feature,mean_shap,reason
0,cashflow.balance_trend_slope,0.079873,Negative balance trajectory
1,income.income_regularity_score,0.027415,Irregular income pattern
2,cashflow.end_of_month_stress_score,0.022538,Month-end cash flow stress
3,emi.missed_emi_signals_count,0.017362,Prior missed EMI signals
4,cashflow.min_balance_30d_inr,0.010788,None
5,emi.loan_stacking_signals,0.006570,Multiple new loans in 30 days (stacking)
6,cashflow.avg_days_to_near_zero,0.005874,Rapid cash depletion after payday
7,emi.bnpl_activity_detected,0.000512,None

## Inference: Apply Models to DataFrame
Load the trained models from their artifacts and score the entire dataset to calculate the BFS Score and RPS probability.

In [ ]:
import xgboost as xgb
from python.training.features import prepare_features
from python.scoring.scoring import probability_to_bfs

# Prepare features
X_bfs = prepare_features(df, BFS_FEATURES)
X_rps = prepare_features(df, RPS_FEATURES)

# Load models and calculate probabilities
model_bfs = xgb.XGBClassifier()
model_bfs.load_model(bfs_result['model_path'])
df['predicted_bfs_prob'] = model_bfs.predict_proba(X_bfs)[:, 1]
df['bfs_score'] = df['predicted_bfs_prob'].apply(probability_to_bfs)

model_rps = xgb.XGBClassifier()
model_rps.load_model(rps_result['model_path'])
df['predicted_rps_prob'] = model_rps.predict_proba(X_rps)[:, 1]

# Display results
display_cols = ['predicted_bfs_prob', 'bfs_score', 'predicted_rps_prob']
# Include targets if they exist in the dataframe
if BFS_TARGET in df.columns:
    display_cols.insert(0, BFS_TARGET)

display(df[display_cols].head(10))